name: mylove
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  lottie: ^3.1.2
  google_fonts: ^6.2.1
  flutter_staggered_animations: ^1.1.1
  firebase_crashlytics: ^4.0.1
  firebase_analytics: ^11.0.1
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  firebase_messaging: ^15.0.1
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  video_player: ^2.8.7
  audioplayers: ^6.0.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/json/
   - assets/images/
   - assets/video/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
